/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pruebaconex;

import Controladores.ProductoJpaController;
import Controladores.TransaccionJpaController;
import Entidades.Producto;
import Entidades.Transaccion;
import java.text.SimpleDateFormat;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static pruebaconex.CompraForm.txtcantidad;
import static pruebaconex.CompraForm.txtdate;
import static pruebaconex.CompraForm.txtproducto;
import static pruebaconex.CompraForm.txtvalorU;

// TODO: Auto-generated Javadoc
/**
 * The Class VentaForm.
 *
 * @author joans
 */
public class VentaForm extends javax.swing.JFrame {

    /** The C producto. */
    ProductoJpaController CProducto = new ProductoJpaController();
    
    /** The C transaccion. */
    TransaccionJpaController CTransaccion = new TransaccionJpaController();
    
    /** The p edit. */
    Producto pEdit;

    /**
     * Creates new form VentaForm.
     */
    public VentaForm() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
    }

    /**
     * Traer nombre.
     *
     * @param nombre the nombre
     * @return the int
     */
    //FUNCION QUE ME PASO MANUEL 
    public int traerNombre(String nombre) {
        List<Producto> listP = CProducto.findProductoEntities();
        for (int i = 0; i < listP.size(); i++) {
            if (listP.get(i).getNombreProducto().equals(nombre)) {
                int resultadoBusqueda = listP.get(i).getIdProducto();
                return resultadoBusqueda;

            }

        }
        return 0;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtdate = new com.toedter.calendar.JDateChooser();
        txtproducto = new javax.swing.JTextField();
        txtcantidad = new javax.swing.JTextField();
        txtvalorU = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nombre producto:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Cantidad:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Valor Unitario:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Fecha: ");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));
        getContentPane().add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, 138, -1));

        txtproducto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtproductoKeyTyped(evt);
            }
        });
        getContentPane().add(txtproducto, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 138, -1));

        txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcantidadActionPerformed(evt);
            }
        });
        txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtcantidadKeyTyped(evt);
            }
        });
        getContentPane().add(txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 138, -1));

        txtvalorU.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalorUKeyTyped(evt);
            }
        });
        getContentPane().add(txtvalorU, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, 138, -1));

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Realizar Venta");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, -1, -1));

        jButton2.setBackground(new java.awt.Color(255, 0, 0));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Cerrar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 10, -1, -1));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Fondo2.jpg"))); // NOI18N
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 400, 300));

        pack();
    } // </editor-fold>//GEN-END:initComponents

    /**
     * Txtcantidad action performed.
     *
     * @param evt the evt
     */
    private void txtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcantidadActionPerformed
        // TODO add your handling code here:
    } //GEN-LAST:event_txtcantidadActionPerformed

    /**
     * J button 1 action performed.
     *
     * @param evt the evt
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        try {
            List<Producto> listP = CProducto.findProductoEntities();
            boolean resp = false; //ESTO ES LA BANDERA PARA SABER SI EL PRODUCTO EXISTE
            int num = 0;
            String nombreP = txtproducto.getText();
            for (int i = 0; i < listP.size(); i++) {

                if (listP.get(i).getNombreProducto().equals(txtproducto.getText())) {
                    resp = true;
                    num = i;
                }
            }
            if (resp != true) { //VA A VENDER UN PRODUCTO QUE NO EXISTE:
                JOptionPane.showMessageDialog(null, "Estás intentando vender un articulo que no existe!\nRevisa tu inventario.", "ERROR", JOptionPane.WARNING_MESSAGE);

            } else {
                //Obtenemos el valor total y la cantidad que tenemos hasta ahora en inventarios.
                int cantidadTotal = listP.get(num).getCantidadAlmacenada();

                //Obtenemos el valor total de la compra que acabamos de realizar
                int cantidadCompra = Integer.parseInt(txtcantidad.getText());

                int resultado = cantidadTotal - cantidadCompra;
                if (resultado < 0) {
                    JOptionPane.showMessageDialog(null, "Lo sentimos, no tenemos esa cantidad.\nActualmente solo le podemos vender " + cantidadTotal + " unidades de ese articulo.", "Total excedido", JOptionPane.INFORMATION_MESSAGE);

                    int respuesta = JOptionPane.showConfirmDialog(null, "¿Desea realizar una compra por esta cantidad?", "Alerta!", JOptionPane.YES_NO_OPTION);

                    if (respuesta == 0) {
                        int id = traerNombre(nombreP);
                        Transaccion t = new Transaccion();

                        //REALIZAMOS EL REGISTRO DE LOS DATOS EN LA TABLA TRANSACCION
                        t.setNombreProducto(txtproducto.getText());
                        t.setCantidad(Integer.parseInt(txtcantidad.getText()));
                        t.setPrecio(Float.parseFloat(txtvalorU.getText()));

                        //Extraemos la fecha del txtdate
                        t.setFechaT(txtdate.getDate());
                        t.setTipo("salida");

                        CTransaccion.create(t);

                        CProducto.destroy(id);
                        JOptionPane.showMessageDialog(null, "Transacción Exitosa.");
                        JOptionPane.showMessageDialog(null, "El producto ahora se encentra agotado!");
                        this.setVisible(false);
                    } else {
                        this.setVisible(false);
                    }
                } else if (resultado == 0) {
                    int id = traerNombre(nombreP);
                    Transaccion t = new Transaccion();

                    //REALIZAMOS EL REGISTRO DE LOS DATOS EN LA TABLA TRANSACCION
                    t.setNombreProducto(txtproducto.getText());
                    t.setCantidad(Integer.parseInt(txtcantidad.getText()));
                    t.setPrecio(Float.parseFloat(txtvalorU.getText()));

                    //Extraemos la fecha del txtdate
                    t.setFechaT(txtdate.getDate());
                    t.setTipo("salida");

                    CTransaccion.create(t);

                    CProducto.destroy(id);
                    JOptionPane.showMessageDialog(null, "Transacción Exitosa.");
                    JOptionPane.showMessageDialog(null, "El producto ahora se encentra agotado!");
                    this.setVisible(false);
                } else {

                    int id = traerNombre(nombreP);
                    Transaccion t = new Transaccion();

                    //REALIZAMOS EL REGISTRO DE LOS DATOS EN LA TABLA TRANSACCION
                    t.setNombreProducto(txtproducto.getText());
                    t.setCantidad(Integer.parseInt(txtcantidad.getText()));
                    t.setPrecio(Float.parseFloat(txtvalorU.getText()));

                    //Extraemos la fecha del txtdate
                    t.setFechaT(txtdate.getDate());
                    t.setTipo("salida");

                    CTransaccion.create(t);

                    float valorTotal = listP.get(num).getValorUnitario() * cantidadTotal;

                    float valorTotalC = Float.parseFloat(txtvalorU.getText()) * cantidadCompra;

                    //Actualizamos el valor total y la cntidad de inventario (Producto)
                    valorTotal = valorTotal - valorTotalC;
                    float valorUnitario = valorTotal / resultado; //Este es el costo unitario
                    Producto pEdit = CProducto.findProducto(id);
                    pEdit.setCantidadAlmacenada(resultado);
                    pEdit.setValorUnitario(valorUnitario);

                    CProducto.edit(pEdit);
                    JOptionPane.showMessageDialog(null, "Transacción Exitosa.");
                    this.setVisible(false);
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage() + e.getCause());
        }
    } //GEN-LAST:event_jButton1ActionPerformed

    /**
     * J button 2 action performed.
     *
     * @param evt the evt
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.setVisible(false);
    } //GEN-LAST:event_jButton2ActionPerformed

    /**
     * Txtproducto key typed.
     *
     * @param evt the evt
     */
    private void txtproductoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtproductoKeyTyped
        char c = evt.getKeyChar();

        if ((c < 'a' || c > 'z') && (c < 'A' || c > 'Z')) {
            evt.consume();
        }
    } //GEN-LAST:event_txtproductoKeyTyped

    /**
     * Txtcantidad key typed.
     *
     * @param evt the evt
     */
    private void txtcantidadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcantidadKeyTyped
        char c = evt.getKeyChar();
       
       if(c < '0' || c > '9') evt.consume();
    } //GEN-LAST:event_txtcantidadKeyTyped

    /**
     * Txtvalor U key typed.
     *
     * @param evt the evt
     */
    private void txtvalorUKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalorUKeyTyped
        char c = evt.getKeyChar();
       
       if(c < '0' || c > '9') evt.consume();
    } //GEN-LAST:event_txtvalorUKeyTyped

    /**
     * The main method.
     *
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaForm().setVisible(true);
            }
        });
    }

    /** The j button 1. */
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    
    /** The j button 2. */
    private javax.swing.JButton jButton2;
    
    /** The j label 1. */
    private javax.swing.JLabel jLabel1;
    
    /** The j label 2. */
    private javax.swing.JLabel jLabel2;
    
    /** The j label 3. */
    private javax.swing.JLabel jLabel3;
    
    /** The j label 4. */
    private javax.swing.JLabel jLabel4;
    
    /** The j label 5. */
    private javax.swing.JLabel jLabel5;
    
    /** The txtcantidad. */
    private javax.swing.JTextField txtcantidad;
    
    /** The txtdate. */
    private com.toedter.calendar.JDateChooser txtdate;
    
    /** The txtproducto. */
    private javax.swing.JTextField txtproducto;
    
    /** The txtvalor U. */
    private javax.swing.JTextField txtvalorU;
    // End of variables declaration//GEN-END:variables
}
